### ISSUE TITLE
.DS_Store uit cache van repository verwijderen

### ISSUE THREAD

**Issue by Mawrengow** [Bram-ter/web-app-from-scratch-2223#1]
.DS_Store is netjes toegevoegd aan je .gitignore, alleen staat deze nog wel in je repository. Met git rm –cached <filename> kan je deze uit je cache verwijderen. 

https://linuxhint.com/clear-git-local-cache/#:~:text=Conclusion-,To%20clear%20the%20Git%20local%20cache%2C%20first%2C%20open%20the%20Git,cached%20%E2%80%9D%20command.

**Comment by Bram-ter** [comment]
Top, bedankt voor de tip 😄
