### ISSUE TITLE
Scheid je code in modules voor meer overzicht

### ISSUE THREAD

**Issue by MelvinIdema** [Bram-ter/web-app-from-scratch-2223#4]
In je main JS bestand _script.js_ heb je op dit moment al je code in 1 bestand staan. Voor de paar lijntjes JavaScript die je op dit moment hebt is dat nog geen probleem maar als je applicatie groeit komende weken kun je makkelijk het overzicht verliezen. Probeer je routing en je data te scheiden van elkaar in modules.

https://github.com/Bram-ter/web-app-from-scratch-2223/blob/f9fd1fd4cb44253254c89430c43bd46b9f104ff4/spa/js/script.js#L59-L87

**Comment by Bram-ter** [comment]
Gedaan 👍
