### ISSUE TITLE
Onnodige code

### ISSUE THREAD

**Issue by MelvinIdema** [Bram-ter/web-app-from-scratch-2223#5]
Deze twee functies lijken onnodig te zijn doordat je op lijn 34 de variable _data_ vult met de response van je API. Verder gebruik je de functies niet. Voor je eigen overzicht is het handig om deze te verwijderen. 

Verder zou je je code eens stapsgewijs kunnen nalopen en kijken wat nou wel en niet nodig is. Het zou allemaal een stuk simpeler kunnen. 

https://github.com/Bram-ter/web-app-from-scratch-2223/blob/f9fd1fd4cb44253254c89430c43bd46b9f104ff4/spa/js/script.js#L5-L20

**Comment by Bram-ter** [comment]
Bedankt voor de tip! helft van deze code was inderdaad niet nodig 👌
