### ISSUE TITLE
Vermijd globals of hernoem naar een uniekere naam

### ISSUE THREAD

**Issue by MelvinIdema** [Bram-ter/web-app-from-scratch-2223#6]
Op dit moment heb je op lijn 3 een _global variable_ gemaakt genaamd _data_ die je vervolgens vult in je functie `getData()`. Echter is het een [_best practice_](https://stackoverflow.com/questions/10525582/why-are-global-variables-considered-bad-practice) om global variables te vermijden. Zeker een global variable genaamd `data`. Want in al je functies zal data nu wijzen naar dit variable. 

Je zou beter de functie return value kunnen gebruiken in een andere functie. Tenzij je hier natuurlijk een goede reden voor hebt. Bijvoorbeeld het vermijden van meerdere API calls. Dan kun je beter een uniekere naam geven aan je variable. 

Kijk ook eens naar `localStorage` voor _state management_. 

https://github.com/Bram-ter/web-app-from-scratch-2223/blob/f9fd1fd4cb44253254c89430c43bd46b9f104ff4/spa/js/script.js#L34

**Comment by Bram-ter** [comment]
Code wat omgegooid, en nu is hij niet meer nodig 👍
